### ISSUE TITLE
log files to stdout

### ISSUE THREAD

**Issue by jtarchie** [leafo/heroku-openresty#2]
I contacted Heroku support and found out, probably like you, that we are not able to use `/dev/stdout` when we want to display our logs. Of course they recommend just tailing the logs, which of course can eat up the file system available.

What do you use for accessing your logs?

I've opened an issue on https://github.com/agentzh/ngx_openresty/issues/7 to see if @agentzh has any insight.

**Comment by leafo** [comment]
I write logs to standard out and use `heroku logs`. It's less than ideal because it only stores 1500 lines. Writing to disk isn't an option because the dyno filesystem is ephemeral.

I have a separate exception tracking module I wrote for lapis that emails me exceptions as they happen. It's very useful but I haven't released it yet.

**Comment by jtarchie** [comment]
How are you using stdout from nginx.conf?

I tried something like the following, but nothing is getting pushed to `heroku logs`. :frowning: Only the standard `heroku[router]` logs are making it.

```
  access_log stdout;
  error_log stderr;
```

This is fun debugging isn't it?

**Comment by jtarchie** [comment]
Nevermind, sorry. Wrong error level set on `error_log`. And `access_log` does support stdout, most likely don't need it because the `heroku[router]` has enough information.
